platform: x64

init:
- git --version
  
install:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=%PATH%;C:\Program Files\Git\mingw64\bin

# Update GIT submodules
- git submodule update --init --recursive

# Download latest stable Stack tool
- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe
- stack --version

# Install Microsoft Z3 from NuGet
# - nuget install z3x64win -Version 4.8.7	
# - dotnet add C:\projects\liquidhaskell\ package Microsoft.Z3.x64 --version 4.8.7
# - set PATH=%PATH%;%cd%;%cd%\z3x64win.4.5.0.1\tools
# - z3 --version

# Download latest stable z3
- curl -sS -oz3.zip -L --insecure  https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-win.zip
- 7z x z3.zip
# - echo %CD%
# - DIR
- set PATH=%PATH%;C:\projects\liquidhaskell\z3-4.8.7-x64-win\bin
- z3 --version


build_script:
# Build LiquidHaskell
- echo "" | stack --no-terminal build --copy-bins --local-bin-path .

# Copy runtime DLLs
- call appveyor-copy.bat

# Test if they are working
- fixpoint --version
- liquid --version

# ZIP execturable 
- 7z a liquidhaskell.zip liquid.exe fixpoint.exe .\include\CoreToLogic.lg LICENSE LICENSE_Z3 libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\bin\*.exe 

test_script:
- echo "" | stack --no-terminal test liquidhaskell --fast --test-arguments "-p Micro"

artifacts:
- path: liquidhaskell.zip
  name: LiquidHaskell
